### ISSUE TITLE
No Sync

### ISSUE THREAD

**Issue by Zaar87** [paprika-network/paprikacoin#2]
This issue tracker is only for technical issues related to Ravencoin.

General Ravencoin questions and/or support requests and are best directed to the [Ravencoin Discord](https://discord.gg/jn6uhur)).

For reporting security issues, please direct message one of the core developers in discord.

### Describe the issue:

When I start Paprikacoin Core the block list cannot be downloaded. This means I cannot synchronize or use my Wallet

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of Ravencoin are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distributio
![Screenshot 2023-10-04 185442](https://github.com/paprika-network/paprikacoin/assets/146981740/dd493050-9816-4c85-926f-7af70c083b51)
![Screenshot 2023-10-04 185413](https://github.com/paprika-network/paprikacoin/assets/146981740/7c34a217-b655-4dc0-85da-ef339fa30a91)
n package such as PPA.

### Machine specs:
- OS: Windows 10
- CPU: i7 11700
[debug.log](https://github.com/paprika-network/paprikacoin/files/12806167/debug.log)

- RAM:
- Disk size: 2 TB
- Disk Type (HD/SDD): M.2 HDD

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

Firewall and Antivirus was deaktivatet while testing

**Comment by ballsconnoisseur** [comment]
Go to discord for more fast response! 
https://discord.com/invite/jgrXwraV65

**Comment by Zaar87** [comment]
Manual add of node solve Problems: 
![image](https://github.com/paprika-network/paprikacoin/assets/146981740/e43f80b5-afc7-4e75-bbd1-572587defc2b)

**Comment by paprika-network** [comment]
Fixed in current version
